CREATE DATABASE SIS2402;

USE SIS2402;

CREATE TABLE CLIENTES
(
	`ID_number` INT auto_increment,
	`NOME` MEDIUMTEXT NOT NULL,
    `GENERO` VARCHAR(10) not null,
    `EMAIL` VARCHAR(50) NOT NULL,
    `NASCIMENTO` DATE NOT NULL,
    `RUA` VARCHAR(50) NOT NULL,
    `NUMERO` INT,
    `BAIRRO` VARCHAR(50) NOT NULL,
    `CIDADE` MEDIUMTEXT	NOT NULL,
    `ESTADO` VARCHAR(2) NOT NULL,
    `PAIS` VARCHAR(50) NOT NULL,
    `CEP` INT,
    
    PRIMARY KEY (`ID_NUMBER`)
);
INSERT INTO `SIS2402` . `CLIENTES`
(
`NOME`, `GENERO`, `EMAIL`, `NASCIMENTO`, 
`RUA`, `NUMERO`, `BAIRRO`, `CIDADE`, `ESTADO`, `PAIS`, `CEP`
);
VALUES 
(`
Vinicius fantin`, `Masculino`, `vinifantitn302@gmail.com`, `20030520`, 
`Ernesto Paese`, `200`, `Universitario`, `videira`, `Santa Catarina`, `Brasil`, `89566254`
);
SELECT * FROM `sis2402` . `CLIENTES`